config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcome#index'

  get 'events/joined'
  resources :events do 
    member do
      put "add-guest/:user_id", action: :add_guest, as: :add_guest
    end
  end

  resources :tasks do 
    member do
      put "add-task/:user_id", action: :add_task, as: :add_task
    end
  end

   resources :tasks do 
    member do
      put "complete-task/", action: :complete_task, as: :complete_task
    end
  end

  resources :events do
    resources :tasks
  end

  resources :users do
    resources :tasks
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :tasks
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_and_belongs_to_many :events
  has_many :tasks
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		@events = Event.all
	end


	def joined
		@user = current_user
		@events = @user.events
	end

	def show
		@event = Event.find(params[:id])
		@guests = @event.users
		@hash = Gmaps4rails.build_markers(@event) do |event, marker|
  			marker.lat event.latitude
  			marker.lng event.longitude
		end
		@uncompleted_tasks = @event.tasks.where(completed: false)
		@completed_tasks = @event.tasks.where(completed: true)
	end

	def new
		@event = Event.new
		@event.host_id = current_user.id
	end

	def create
		@event = Event.new(events_params)
		@event.host_id = current_user.id

		if @event.save
			redirect_to events_path
		else
			render 'new'
		end
	end


	def add_guest
  		event = Event.find(params[:id])
	  	guest = User.find(params[:user_id]) 

  		event.users << guest unless event.users.include?(guest) # Make sure there are no duplicates in the join table

  		redirect_to event_path(event) # change this to whatever route you like
	end

	private
	def events_params
		params.require(:event).permit(:name, :description, :address, :date, :host_id)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def show
		@task = Task.find(params[:id])
		@event = @task.event
	end

	def new
		@task = Task.new
		@event = Event.find(params[:event_id])
	end

	def create
		@event = Event.find(params[:event_id])

		@task = @event.tasks.create(task_params)
		if @task.save
			redirect_to event_path(@event)
		else
			render 'new'
		end
	end

	def index
		@user = current_user
		@tasks = @user.tasks
	end



	def add_task
  		task = Task.find(params[:id])

	  	guest = User.find(params[:user_id]) 

  		task.user_id = guest.id
  		task.save

  		redirect_to event_task_path(task.event, task) # change this to whatever route you like
	end

	def complete_task
		task = Task.find(params[:id])
		task.completed = true
		task.save

		redirect_to event_task_path(task.event, task)
	end
	
	private
	def task_params
		params.require(:task).permit(:name, :description)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/index.html.erb
<style type="text/css">
	.buttons{
		text-align: center;
	}
</style>

<h1 class="page-title">All Events</h1>

<h3 class="buttons"> <%= link_to 'New Event', new_event_path, :class=>"button small success" %> <%= link_to 'My Events', events_joined_path, :class=>"button small success" %> </h3>

<% @events.each do |event| %>
	
	<h3> <%= link_to event.name, event_path(event), 'data-no-turbolink' => true %>	</h3>
	<p>	<%= event.date.to_date.strftime("%B %d") %>	 @ <%= event.date.strftime("at %I:%M%p") %></p>


<% end %>

app/views/events/joined.html.erb
<style type="text/css">
	.buttons{
		text-align: center;
	}
</style>

<h1 class="page-title">My Events</h1>

<h3 class="buttons"> <%= link_to 'New Event', new_event_path, :class=>"button small success" %> <%= link_to 'All Events', events_path, :class=>"button small success" %> </h3>

<% @events.each do |event| %>

	
	<h3> <%= link_to event.name, event_path(event), 'data-no-turbolink' => true %>	</h3>
	<p>	<%= event.date.to_date.strftime("%B %d") %>	 @ <%= event.date.strftime("at %I:%M%p") %></p>


<% end %>

app/views/events/new.html.erb
<style type="text/css">
form{
	margin-top: 20px;
	margin-left: 35px;
   	margin-right: 35px;
}

</style>
<h1 class="page-title">Create an event</h1>

<%= form_for @event, html: {multipart: true} do |f| %>

	<%= f.text_field :name, :placeholder => "Fourth of July Bonfire", size: 25 %> <br />
	<%= f.text_field :address, :placeholder => "23 Townline Rd, East Hampton", size: 25 %> <br />
	<%= f.text_area :description, :placeholder => "Let's celebrate America's birthday around a fire. There will be beer, marshmallows, and friends", rows: 3, cols: 27%> <br />
	<%= f.datetime_select :date, start_year: 2015, ampm: true, :minute_step => 15, :class => 'dts'	 %> <br />
	<%= f.submit "create", :class=>"btn btn-primary"%> <br />

<% end %>

app/views/events/show.html.erb
<style type="text/css">
	.by{
		text-align: center;
	}
</style>

<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


 <h1 class="page-title"> <%= @event.name %> </h1>
 <h4 class="by"> <i> Hosted by: <%= User.find(@event.host_id).first_name %> </i></h4> <br />
 <h3>On:  <%= @event.date.to_date.strftime("%B %d") %>	 @ <%= @event.date.strftime("at %I:%M%p") %> </h3>

	<div style='width: 800px;'>
  <div id="map" style='width: 500px; height: 200px;'></div>
</div>
 <h3> Description: </h3>
 <p> <%= @event.description %></p>

<h3> <%= @event.users.size %> guests: </h3>
<% @event.users.each do |guest| %>
	<p> <%= guest.email %> </p>
<% end %>

<% if !(@event.users.include?(current_user)) %>
	<%= link_to "Join Event", add_guest_event_path(event: @event, user_id: current_user.id), method: :put %>
<% end %>

<h3> Pending Tasks: </h3>

<% @uncompleted_tasks.each do |task| %>
	
	<h3> <%= link_to task.name, event_task_path(task.event, task)%>	</h3>

<% end %>

<% if (current_user.id == @event.host_id) %>
	<p> <%= link_to 'Add Task', new_event_task_path(@event) %> </p>
<% end %>

<h3> Complete Tasks: </h3>
<% @completed_tasks.each do |task| %>
	
	<h3> <%= link_to task.name, event_task_path(task.event, task)%>	</h3>

<% end %>


<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(15);
});
</script>

app/views/layouts/application.html.erb
<style type="text/css">
.icon-bar{
  margin-bottom: 0px;
  bottom: 0;
  position: fixed;
  width: 100%;
}

</style>


<!DOCTYPE html>
<html lang="en">
  <head>
  	<link href='http://fonts.googleapis.com/css?family=Oswald:700' rel='stylesheet' type='text/css'>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>


	
    <%= yield %>

		<br />
		<br />
		<br />
  </body>

<% if user_signed_in? %>
	<div class="icon-bar three-up menu">
	<%= link_to '<i class="fi-calendar"></i>'.html_safe, events_joined_path, class: "item"%>
  	<%= link_to '<i class="fi-list-thumbnails"></i> '.html_safe, user_tasks_path(current_user), class: "item"%>
  	<%= link_to '<i class="fi-torso"></i>'.html_safe, root_path, class: "item"%>
  </div>
<% end %>
</html>

app/views/tasks/index.html.erb
<h1 class="page-title">My Tasks</h1>

<% @tasks.each do |task| %>
	
	<h3> <%= link_to task.name, event_task_path(task.event, task)%>	</h3>
	<p>	Due: <%= task.event.date.to_date.strftime("%B %d") %>	 @ <%= task.event.date.strftime("at %I:%M%p") %></p>


<% end %>

app/views/tasks/new.html.erb
<style type="text/css">
body{
   margin-left: 35px;
   margin-right: 35px;
}
</style>
<h1 class="page-title">add a task to <%= @event.name %> </h1>

<div class='form'>≈
<%= form_for [@event, @task] do |f| %>
	<div class="field">
	<%= f.text_field :name, :placeholder => "Task Name", size: 25 %> <br />
	</div>
	<div class="field">
	<%= f.text_area :description, :placeholder => "Short Description", rows: 3, cols: 27%> <br />
	</div>
	<div class="field">
	<%= f.submit "create", :class=>"btn btn-primary"%> <br />
	</div>
<% end %>
</div>

app/views/tasks/show.html.erb
<h1 class="page-title"> <%= @task.name %> </h1>

<h4> <%= @task.description %> </h4>

<% if (@task.user == nil) %>
	<%= link_to "Pickup Task", add_task_task_path(task: @task, user_id: current_user.id), method: :put %>
<% else %>
	<p> 
	<% if @task.completed %> 
	Completed
	<%else %>
	Accepted
	<%end %>
	by: <%= @task.user.first_name %> <%= @task.user.last_name %></p>
<% end %>

<% if (!@task.completed && @task.user == current_user) %> 
<%= link_to "Complete Task", complete_task_task_path(task: @task), method: :put %>
<% end %>

app/views/welcome/index.html.erb
<h1 class="page-title"> Welcome, <%= current_user.email %></h1>

<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>